### ISSUE TITLE
Display the subnet the match was found in

### ISSUE THREAD

**Issue by niekvlessert** [goncalor/grepcidr#1]
I would like the program to show the subnet the match was found in, without scanning 100 times using a while loop in bash. Tried to fix it myself but couldn't do it. Any ideas how to achieve this?

**Comment by goncalor** [comment]
Hey. I believe what you're looking for is the flag `-p`.

The current code in this repo is based on the original `grepcidr` code with the only difference that I added that option. If you think it's useful let me know.

https://github.com/goncalor/grepcidr/blob/23b999cc0b86cce2e650b8b029e55af1cc55ba06/README#L43

**Comment by niekvlessert** [comment]
Wow, great! I must confess I didn't look at your version, I just tried to find a version of grepcidr on Github that allowed me to create a ticket for it. And now your version contains just the option I was wishing for. What a coincidence. I'll let you know! Maybe add some response to this url so people know this modified version exists, I didn't find it as of yet. Those solutions are slow (and some are bad); https://unix.stackexchange.com/questions/274330/check-ip-is-in-range-of-whitelist-array.

**Comment by goncalor** [comment]
If this helps that's great news! I like `grepcidr` but felt multiple times an option like this was missing. If this is useful for more people I may contact the original author, Jem Berkes, to see if they'd like to merge (the original is not on GitHub).

I haven't benchmarked both versions, but I believe performance should be close to the original (a bit slower when using `-p`).

Thanks for the suggestion. May consider adding a response.

**Comment by goncalor** [comment]
I tried to contact Jem Berkes but haven't heard back from them so far.
Will close this issue.
