### ISSUE TITLE
newline with -p

### ISSUE THREAD

**Issue by niekvlessert** [goncalor/grepcidr#2]
I needed to do something now that needed your additions and they work just fine, so many thanks. Might consider adding a \n when printing the pattern with -p. I wanted to uniq -c the results.

**Comment by goncalor** [comment]
Hi. Thanks.

It seems the bug you're describing happens when providing the pattern as an argument (and not via file).

This works fine:
```
./grepcidr -pf patterns.txt ips.txt
10.0.0.0/8
127.0.0.0/8
```

However, this does not:
```
./grepcidr -p '10.0.0.0/8 127.0.0.1/8' ips.txt
10.0.0.0/8127.0.0.0/8
```

I will try to fix this soon. In the meantime, as a workaround, I suggest you specify the patterns via file with `-f`.

**Comment by niekvlessert** [comment]
Ah, interesting! I already added the \n in the code, but that fix will need
some more thinking then...

Op za 29 aug. 2020 11:48 schreef Gonçalo Ribeiro <notifications@github.com>:

**Comment by goncalor** [comment]
Should be fixed now. Try it when you can. Thanks.
